# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            '’blunch'
tagline:          'A Jekyll theme'
description:      'A site about the pub lunch, henceforth to be known as “blunch”. Written by two people who love a blunch far too much.'
url:              https://blunchblog.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
